version: "3.7"

networks:
  dysn:
    name: docker_dysn

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - ${POSTGRES_PORT:-5433}:5432
    volumes:
      - dysn_auth_db:/var/lib/postgresql/data
    networks:
      - dysn


  dysn_auth:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - dysn
    ports:
      - "5301:5301"
    volumes:
      - dysn_auth:/var/www/html/dysn/auth

volumes:
  dysn_auth:
  dysn_auth_db:
